#!/usr/bin/env bash
# package.sh --portal-url https://<library-address> [--version X.Y.Z]
# Builds the "Library Upload" plug-in for VMware Cloud Director 10.6 and writes
# library-upload-plugin-<version>.zip, ready for Customize Portal > Upload.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
die() { echo "ERROR $*" >&2; exit 1; }

url="" version=""
while (( $# )); do
  case $1 in
    --portal-url) url=${2:?--portal-url needs the library address}; shift 2 ;;
    --version) version=${2:?--version needs X.Y.Z}; shift 2 ;;
    -h|--help) sed -n '2,4p' "${BASH_SOURCE[0]}" | sed 's/^# //'; exit 0 ;;
    *) die "unknown option $1" ;;
  esac
done
url=${url%/}
[[ $url =~ ^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?$ ]] \
  || die "--portal-url must be the library's https address without a path, e.g. https://vcsp.example.local"
command -v node >/dev/null || die "Node.js 18 or 20 is required (Broadcom's template builds with node:18.20); or use the Dockerfile"
major=$(node -p 'process.versions.node.split(".")[0]')
[[ $major == 18 || $major == 20 ]] || echo "WARN Node.js $major is outside Angular 17's supported range (18, 20); prefer the Dockerfile" >&2
version=${version:-$(node -p "require('./package.json').version")}
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "--version must look like 1.2.3"

printf '// Generated by package.sh - the content library address this plug-in opens.\nexport const PORTAL_BASE_URL = "%s";\n' "$url" > src/main/portal-config.ts
node -e '
  const fs = require("fs"), f = "src/public/manifest.json", m = JSON.parse(fs.readFileSync(f, "utf8"));
  m.version = process.argv[1]; m.link = process.argv[2] + "/";
  fs.writeFileSync(f, JSON.stringify(m, null, 4) + "\n");' "$version" "$url"

if [[ ! -d node_modules ]]; then
  if [[ -f package-lock.json ]]; then npm ci --no-audit --no-fund; else npm install --no-audit --no-fund; fi
fi
npm test --silent
rm -rf dist
npx ng build
# @vcd/plugin-builders writes the upload package itself: dist/plugin.zip = manifest.json + bundle.js
node -e '
  const z = require("fs").readFileSync("dist/plugin.zip");
  for (const n of ["manifest.json", "bundle.js"]) if (!z.includes(Buffer.from(n))) { console.error("dist/plugin.zip lacks " + n); process.exit(1); }' \
  || die "the build did not produce a complete dist/plugin.zip"

out="library-upload-plugin-$version.zip"
rm -f "$out" "$out.sha256"
cp dist/plugin.zip "$out"
sha256sum "$out" > "$out.sha256"
echo "Built $out for $url"
